version: '3.9'
services:
  users-service:
    container_name: nestjs_user_service
    image: nestjs-user-service:0.1.0
    init: true
    build:
      context: ../user
      dockerfile: dockerfile
      target: dev
    restart: unless-stopped
    env_file:
      - ../Setup.env
    command: npm run start:dev
    depends_on:
      - db
    volumes:
      - ../user:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - infra
    ports:
      - 3000:3000
      - 9229:9229

  db:
    image: postgres:15.1-alpine
    container_name: infra-db
    restart: unless-stopped
    env_file:
      - ../Setup.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - infra
    ports:
      - 5432:5432

volumes:
  pgdata:


networks:
  infra:


